#!/bin/sh
# I3WMCTL script for I3WM
# uses Dmenu
# By Youri Claes | CupOfCoffee

OP=$(echo -e "Restart\nReload\nLock\nReboot\nExit\nPoweroff\nSuspend" | dmenu -b -i -p "Totalctl")

case $OP in

    Restart)       restart-all                                                                          ;;
    Reload)        i3-msg reload                                                                            ;;
    Lock)          I3LOCK_RICE                                                                              ;;
    Reboot)        systemctl reboot                                                                         ;;
    Poweroff)      systemctl poweroff                                                                       ;;
    Suspend)       systemctl suspend                                                                        ;;
    Exit)          exit                                                                                     ;;
    *)             echo "That's an incorrect option" | dmenu -b -i -p "Error"& PID=$!; sleep 2; kill $PID   ;;

esac
 
