#!/bin/sh

case $1 in
	Ge) BOOK='1' ;;
	Ex) BOOK='2' ;;
	Le) BOOK='3' ;;
	Nu) BOOK='4' ;;
	De) BOOK='5' ;;
	Joz) BOOK='6' ;;
	Re) BOOK='7' ;;
	Ru) BOOK='8' ;;
	1Sa) BOOK='9' ;;
	2Sa) BOOK='10' ;;
	1Kon) BOOK='11' ;;
	2Kon) BOOK='12' ;;
	1Kr) BOOK='13' ;;
	2Kr) BOOK='14' ;;
	Ezr) BOOK='15' ;;
	Ne) BOOK='16' ;;
	Es) BOOK='17' ;;
	Job) BOOK='18' ;;
	Ps) BOOK='19' ;;
	Sp) BOOK='20' ;;
	Pr) BOOK='21' ;;
	Hgl) BOOK='22' ;;
	Jes) BOOK='23' ;;
	Jer) BOOK='24' ;;
	Klg) BOOK='25' ;;
	Ez) BOOK='26' ;;
	Da) BOOK='27' ;;
	Ho) BOOK='28' ;;
	Joë) BOOK='29' ;;
	Am) BOOK='30' ;;
	Ob) BOOK='31' ;;
	Jon) BOOK='32' ;;
	Mi) BOOK='33' ;;
	Na) BOOK='34' ;;
	Hab) BOOK='35' ;;
	Ze) BOOK='36' ;;
	Hag) BOOK='37' ;;
	Za) BOOK='38' ;;
	Mal) BOOK='39' ;;
	Mt) BOOK='40' ;;
	Mr) BOOK='41' ;;
	Lu) BOOK='42' ;;
	Jo) BOOK='43' ;;
	Han) BOOK='44' ;;
	Ro) BOOK='45' ;;
	1Kor) BOOK='46' ;;
	2Kor) BOOK='47' ;;
	Ga) BOOK='48' ;;
	Ef) BOOK='49' ;;
	Fil) BOOK='50' ;;
	Kol) BOOK='51' ;;
	1Th) BOOK='52' ;;
	2Th) BOOK='53' ;;
	1Ti) BOOK='54' ;;
	2Ti) BOOK='55' ;;
	Tit) BOOK='56' ;;
	Flm) BOOK='57' ;;
	Heb) BOOK='58' ;;
	Jak) BOOK='59' ;;
	1Pe) BOOK='60' ;;
	2Pe) BOOK='61' ;;
	1Jo) BOOK='62' ;;
	2Jo) BOOK='63' ;;
	3Jo) BOOK='64' ;;
	Ju) BOOK='65' ;;
	Opb) BOOK='66' ;;
    *) chromium --app https://wol.jw.org/nl/wol/binav/r18/lp-o ;; 
esac

echo $2 > $HOME/tekst.temp
sed -i "s/:/\ /g" $HOME/tekst.temp
H=$(awk '{ NR==1 } { print $1 }' $HOME/tekst.temp)
V=$(awk '{ NR==1 } { print $2 }' $HOME/tekst.temp)

chromium --app https://wol.jw.org/nl/wol/b/r18/lp-o/nwtsty/O/2018/$BOOK/$H#study=discover\&v=$BOOK:$H:$V

rm $HOME/tekst.temp
