#!/bin/sh
# DEFAULT BY AUTHOR POLYBAR

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1
polybar -r top &

echo "Bars launched..."
